import type { App } from "vue";
import PrimeVue from "primevue/config";
import Aura from "@primevue/themes/aura";
import ToastService from "primevue/toastservice";
import ConfirmationService from "primevue/confirmationservice";

// Polska lokalizacja
const polishLocale = {
    startsWith: "Zaczyna się od",
    contains: "Zawiera",
    notContains: "Nie zawiera",
    endsWith: "Kończy się na",
    equals: "Równa się",
    notEquals: "Nie równa się",
    noFilter: "Brak filtra",
    lt: "Mniejsze niż",
    lte: "Mniejsze lub równe",
    gt: "Większe niż",
    gte: "Większe lub równe",
    dateIs: "Data to",
    dateIsNot: "Data nie jest",
    dateBefore: "Data przed",
    dateAfter: "Data po",
    clear: "Wyczyść",
    apply: "Zastosuj",
    matchAll: "Dopasuj wszystkie",
    matchAny: "Dopasuj dowolne",
    addRule: "Dodaj regułę",
    removeRule: "Usuń regułę",
    accept: "Tak",
    reject: "Nie",
    choose: "Wybierz",
    upload: "Wgraj",
    cancel: "Anuluj",
    dayNames: [
        "Niedziela",
        "Poniedziałek",
        "Wtorek",
        "Środa",
        "Czwartek",
        "Piątek",
        "Sobota",
    ],
    dayNamesShort: ["Nie", "Pon", "Wt", "Śr", "Czw", "Pt", "Sob"],
    dayNamesMin: ["N", "P", "W", "Ś", "C", "P", "S"],
    monthNames: [
        "Styczeń",
        "Luty",
        "Marzec",
        "Kwiecień",
        "Maj",
        "Czerwiec",
        "Lipiec",
        "Sierpień",
        "Wrzesień",
        "Październik",
        "Listopad",
        "Grudzień",
    ],
    monthNamesShort: [
        "Sty",
        "Lut",
        "Mar",
        "Kwi",
        "Maj",
        "Cze",
        "Lip",
        "Sie",
        "Wrz",
        "Paź",
        "Lis",
        "Gru",
    ],
    today: "Dziś",
    weekHeader: "Tydz",
    firstDayOfWeek: 1,
    dateFormat: "dd.mm.yy",
    weak: "Słabe",
    medium: "Średnie",
    strong: "Silne",
    passwordPrompt: "Wpisz hasło",
    emptyFilterMessage: "Brak wyników",
    emptyMessage: "Brak dostępnych opcji",
    aria: {
        trueLabel: "Prawda",
        falseLabel: "Fałsz",
        nullLabel: "Nie wybrano",
        star: "1 gwiazdka",
        stars: "{star} gwiazdek",
        selectAll: "Wybrano wszystkie elementy",
        unselectAll: "Odznaczono wszystkie elementy",
        close: "Zamknij",
        previous: "Poprzedni",
        next: "Następny",
        navigation: "Nawigacja",
        scrollTop: "Przewiń do góry",
        moveTop: "Przenieś na górę",
        moveUp: "Przenieś w górę",
        moveDown: "Przenieś w dół",
        moveBottom: "Przenieś na dół",
        moveToTarget: "Przenieś do celu",
        moveToSource: "Przenieś do źródła",
        moveAllToTarget: "Przenieś wszystko do celu",
        moveAllToSource: "Przenieś wszystko do źródła",
        pageLabel: "{page}",
        firstPageLabel: "Pierwsza strona",
        lastPageLabel: "Ostatnia strona",
        nextPageLabel: "Następna strona",
        prevPageLabel: "Poprzednia strona",
        rowsPerPageLabel: "Wierszy na stronę",
        previousPageLabel: "Poprzednia strona",
        jumpToPageDropdownLabel: "Przejdź do strony",
        jumpToPageInputLabel: "Przejdź do strony",
        selectRow: "Wybrano wiersz",
        unselectRow: "Odznaczono wiersz",
        expandRow: "Rozwiń wiersz",
        collapseRow: "Zwiń wiersz",
        showFilterMenu: "Pokaż menu filtrów",
        hideFilterMenu: "Ukryj menu filtrów",
        filterOperator: "Operator filtra",
        filterConstraint: "Ograniczenie filtra",
        editRow: "Edytuj wiersz",
        saveEdit: "Zapisz zmiany",
        cancelEdit: "Anuluj zmiany",
        listView: "Widok listy",
        gridView: "Widok siatki",
        slide: "Slajd",
        slideNumber: "{slideNumber}",
        zoomImage: "Powiększ obraz",
        zoomIn: "Powiększ",
        zoomOut: "Pomniejsz",
        rotateRight: "Obróć w prawo",
        rotateLeft: "Obróć w lewo",
        chooseDate: "Wybierz datę",
        chooseMonth: "Wybierz miesiąc",
        chooseYear: "Wybierz rok",
        prevDecade: "Poprzednia dekada",
        nextDecade: "Następna dekada",
        prevYear: "Poprzedni rok",
        nextYear: "Następny rok",
        prevMonth: "Poprzedni miesiąc",
        nextMonth: "Następny miesiąc",
        prevHour: "Poprzednia godzina",
        nextHour: "Następna godzina",
        prevMinute: "Poprzednia minuta",
        nextMinute: "Następna minuta",
        prevSecond: "Poprzednia sekunda",
        nextSecond: "Następna sekunda",
        am: "AM",
        pm: "PM",
    },
};

export function registerPrimeVue(app: App): void {
    app.use(PrimeVue, {
        theme: {
            preset: Aura,
            options: {
                darkModeSelector: ".app-dark",
                cssLayer: {
                    name: "primevue",
                    order: "theme, base, primevue",
                },
            },
        },
        locale: polishLocale,
        ripple: true,
    });
    app.use(ToastService);
    app.use(ConfirmationService);
}
